# A simple example for a drupal dork setup. Uses
# a local copy of the Drupal source code and an
# unopinionated php image.
version: '2'

services:
  web:
    image: drupal:8
    labels:
    ports:
    - "80:80"
    links:
    - database:database
    labels:
      dork.root: /var/www/html
      dork.hotcode: modules;themes;profiles

  database:
    image: mysql
    environment:
      # Set hardcoded database user and password.
      # DON'T DO THIS IN PRODUCTION
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: root
