version: '2'

services:

  drush:
    image: drush/drush
    volumes:
    - ${DORK_SOURCE}:/var/www/html
    - files:/var/www/web/sites/default/files
    working_dir: /var/www/html/sites/default
    networks:
    - back
    links:
    - mysql:database

  composer:
    image: composer/composer
    volumes:
    - ${DORK_SOURCE}:/app
    command: install