version: '2'

volumes:
  database:
  public:
  private:

services:

  web:
    build: ./php
    ports:
    - "80:80"
    links:
    - mysql:database
    external_links:
    - dork_aux_dbgp:dbgp
    volumes:
    - public:/var/www/web/sites/default/files
    - private:/private
    - ${DRUPAL_IMPORT_DIR}:/import
    environment:
      DORK_SOURCE_PATH: /source
      DORK_SOURCE_ROOT: /var/www
      DEVELOPMENT: ${DRUPAL_DEVELOPMENT}
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
      DRUPAL_ADMIN_USER: ${DRUPAL_ADMIN_USER}
      DRUPAL_ADMIN_PASS: ${DRUPAL_ADMIN_PASS}
      DRUPAL_INSTALL_PROFILE: ${DRUPAL_INSTALL_PROFILE}
      DRUPAL_INSTALL_PARAMS: ${DRUPAL_INSTALL_PARAMS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mysql:
    image: mysql
    volumes:
    - database:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  composer:
    image: composer/composer
    volumes:
    - ${DORK_SOURCE}:/app
    entrypoint: composer
    command: install

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6.0-2
    links:
    - mysql:db
    ports:
    - 8080:80
